apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: osc81n701-go 
  janus-idp.io/tekton: osc81n701-go
  backstage.io/kubernetes-id: osc81n701-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: osc81n701-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  