apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: osc81n701-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: osc81n701-go 
  name: osc81n701-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: osc81n701-go 
